@echo off
echo ========================================
echo   Process Lasso Configuration Fix
echo   Based on bitsum.com official docs
echo ========================================
echo.
echo This creates prolasso.ini with CORRECT settings.
echo Location determined by the script above.
echo.

REM ========================================
REM CORRECT prolasso.ini FORMAT (from bitsum.com docs)
REM ========================================
echo Creating prolasso.ini...

REM Check where the config should go
set "PL_CONFIG=%APPDATA%\Bitsum\Process Lasso"
if not exist "%PL_CONFIG%" mkdir "%PL_CONFIG%"

echo Saving to %PL_CONFIG%\prolasso.ini

(
echo # prolasso.ini — Process Lasso Configuration
echo # Generated by diagnostic tools
echo # Based on bitsum.com official documentation
echo #
echo [OutOfControlProcessRestraint]
echo OocOn=True
echo TotalProcessorUsageBeforeRestraint=85
echo PerProcessUsageBeforeRestraint=20
echo TimeOverQuotaBeforeRestraint=2800
echo PerProcessUsageForRestore=10
echo TameOnlyNormal=True
echo LowerToIdleInsteadOfBelowNormal=False
echo ExcludeServices=False
echo ExcludeForegroundProcesses=True
echo DoNotLowerPriorityClass=False
echo OocExclusions=
echo.
echo [GUI]
echo HideGraph=False
echo HideProcessIcons=False
echo ShowGraphLegend=True
echo ClearLogAtExit=False
echo.
echo [Performance]
echo ManageOnlyCurrentUser=True
echo ExitOnCloseWindow=False
echo BoostForegroundThread=True
echo BoostForegroundProcess=True
echo SoundsOff=True
echo AggressivelyTrimProcessLassoWorkingSet=True
echo CloseApplicationTimeoutSeconds=10
echo ForcedMode=False
echo.
echo [Updates]
echo CheckForUpdates=False
echo.
echo [SystemTrayIcon]
echo UseStaticIcon=False
echo ShowResponsivnessInTrayInsteadOfProcessorUsage=False
echo.
echo [Logging]
echo LogAllProcessesExecuted=False
echo LogProcessesDisallowed=True
echo LogDefaultPriorityAdjustments=True
echo LogDefaultAffinityAdjustments=True
echo LogOutOfControlProcessesRestrained=True
echo LogOutOfControlProcessesRestored=True
echo LogInstanceLimitTerminations=True
echo MaximumLogEntries=50
echo.
echo [MemoryManagement]
echo TrimAllProcessesAtThisIntervalInMs=30000
echo.
echo [SysTrayBalloons]
echo ShowBalloons=False
echo BalloonTipDuration=10000
echo.
echo [Performance]
echo UpdateSpeed=1000
echo.
echo [ProcessDefaults]
echo DefaultPriorities=brave.exe,above normal;orca.exe,above normal;opencode2.exe,above normal;explorer.exe,normal;svchost.exe,normal;System.exe,normal;csrss.exe,normal;lsass.exe,normal;dwm.exe,normal;textinputhost.exe,normal;StartMenuExperienceHost.exe,normal
echo DefaultAffinities=brave.exe,FFFFFFFF;orca.exe,FFFFFFFF;opencode2.exe,FFFFFFFF;explorer.exe,FFFFFFFF;svchost.exe,FFFFFFFF;System.exe,FFFFFFFF;csrss.exe,FFFFFFFF;lsass.exe,FFFFFFFF;dwm.exe,FFFFFFFF
echo MatchWildcardsToPathnames=False
echo.
echo [ProcessAllowances]
echo AllowedProcesses=
echo DisallowedProcesses=
echo InstanceLimitedProcesses=
echo.
echo [AdvancedRules]
echo WatchdogRules=
) > "%PL_CONFIG%\prolasso.ini"

echo.
echo ========================================
echo   prolasso.ini created successfully!
echo ========================================
echo.
echo Key settings applied:
echo   - ProBalance OOC restraint: ON (85% total CPU threshold)
echo   - Forced Mode: OFF (rules applied once per instance)
echo   - BoostForegroundProcess/Thread: ON (boost active apps)
echo   - AggressivelyTrimProcessLassoWorkingSet: ON (memory trim)
echo   - Trim interval: 30 seconds
echo   - ManageOnlyCurrentUser: TRUE (user processes only)
echo   - DefaultPriorities: brave/orca/opencode = Above Normal
echo   - DefaultAffinities: all 4 FFFs (use all cores)
echo.
echo Restart Process Lasso or run:
echo   ProcessLasso.exe /ConfigFolder="%APPDATA%\Bitsum\Process Lasso" /TrimNow
echo.
echo ========================================
echo   Additional Windows Tweaks (run as admin)
echo ========================================
echo.
echo powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
echo powercfg -setacvalueindex SCHEME_CURRENT SUB_PROCESSOR IDLEDISABLE 1
echo reg add "HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" /v HWSchMode /t REG_DWORD /d 2 /f
echo reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\SubSystems" /v Win32PrioritySeparation /t REG_SZ /d "26" /f
echo bcdedit /set disabledynamictick yes
echo.
pause
